version: '3.8'

x-spark-common: &spark-common
  image: bitnami/spark:3.5.0
  networks:
    - bigdata
  volumes:
    - ./hosts:/etc/hosts
    - ./notebooks:/home/jovyan/notebooks

x-spark-worker: &spark-worker
  <<: *spark-common
  environment:
    - SPARK_MODE=worker
    - SPARK_MASTER_URL=spark://spark-master:7077
    - SPARK_WORKER_MEMORY=1G
    - SPARK_WORKER_CORES=1
    - SPARK_RPC_AUTHENTICATION_ENABLED=no
    - SPARK_RPC_ENCRYPTION_ENABLED=no
    - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
    - SPARK_SSL_ENABLED=no
    - SPARK_NO_DAEMONIZE=true

services:
  spark-master:
    <<: *spark-common
    hostname: spark-master
    container_name: spark-master
    ports:
      - "8090:8080"
    environment:
      - SPARK_MODE=master
      - SPARK_NO_DAEMONIZE=true
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_SSL_ENABLED=no

  spark-worker-1:
    <<: *spark-worker
    hostname: spark-worker-1
    container_name: spark-worker-1
    ports:
      - "8091:8081"

  spark-worker-2:
    <<: *spark-worker
    hostname: spark-worker-2
    container_name: spark-worker-2
    ports:
      - "8092:8081"

  # spark-worker-3:
  #   <<: *spark-worker
  #   hostname: spark-worker-3
  #   container_name: spark-worker-3
  #   ports:
  #     - "8093:8081"

  jupyter:
    image: jupyter-sparksubmit:v01
    container_name: jupyter
    ports:
      - 8888:8888
    volumes:
      - ./notebooks:/home/jovyan/notebooks
    networks:
      - bigdata
    
networks:
  bigdata:
    external: true